/**
 * @file ${FILE}
 * @author Patrick Glöckner
 * @date 12.02.23
*/

#ifndef SOCKETCAN_SRC_TESTUTILITIES_LATENCYMEASUREMENTNODE_H_
#define SOCKETCAN_SRC_TESTUTILITIES_LATENCYMEASUREMENTNODE_H_

class LatencyMeasurementNode {

};

#endif //SOCKETCAN_SRC_TESTUTILITIES_LATENCYMEASUREMENTNODE_H_
